services:
  - type: web
    name: interviewlabs
    env: node
    plan: free
    buildCommand: npm install && pip install -r requirements.txt
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: COHERE_API_KEY
        sync: false
      - key: WHISPER_MODEL
        value: base
      - key: PORT
        value: 10000
